-- GENERATED by db/generate_dev_seed.py - edit the script, not this file.
-- Sample catalogue for local development. Safe to run repeatedly.
BEGIN;

INSERT INTO category (category_name) VALUES ('Electronics'), ('Books'), ('Home'), ('Sports & Outdoors'), ('Beauty') ON CONFLICT (category_name) DO NOTHING;
INSERT INTO brand (brand_name) VALUES ('Acme'), ('Globex'), ('Initech'), ('Northwind'), ('Contoso') ON CONFLICT (brand_name) DO NOTHING;

INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Wireless Headphones', 'Over-ear Bluetooth headphones with 30-hour battery and active noise cancelling.', 129.99, 'USD', 25, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Electronics'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Acme'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Wireless Headphones');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Mechanical Keyboard', 'Tenkeyless keyboard with hot-swappable switches and PBT keycaps.', 89.50, 'USD', 12, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Electronics'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Globex'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Mechanical Keyboard');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'USB-C Charger 65W', 'Compact GaN charger for laptops, tablets and phones.', 39.00, 'USD', 0, 'OUT_OF_STOCK',
       (SELECT category_id FROM category WHERE category_name = 'Electronics'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Initech'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'USB-C Charger 65W');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Smartwatch Active 2', 'Heart-rate, sleep and GPS tracking with a 7-day battery and always-on display.', 199.00, 'USD', 4, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Electronics'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Northwind'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Smartwatch Active 2');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Portable Bluetooth Speaker', 'Waterproof (IP67) speaker with 360-degree sound and 20 hours of playback.', 59.99, 'USD', 31, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Electronics'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Contoso'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Portable Bluetooth Speaker');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Ergonomic Wireless Mouse', 'Silent clicks, 4000 DPI sensor and a contoured grip for long workdays.', 34.99, 'USD', 48, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Electronics'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Globex'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Ergonomic Wireless Mouse');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Mirrorless Camera Z50', '24 MP APS-C sensor, 4K video and a flip-out touchscreen. Body only.', 849.00, 'USD', 3, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Electronics'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Northwind'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Mirrorless Camera Z50');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT '10-inch Tablet', 'Full-HD display, 128 GB storage and all-day battery for reading and streaming.', 279.00, 'USD', 15, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Electronics'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Acme'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = '10-inch Tablet');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Wireless Game Controller', 'Low-latency controller with rumble, works with PC, Android and consoles.', 49.95, 'USD', 0, 'OUT_OF_STOCK',
       (SELECT category_id FROM category WHERE category_name = 'Electronics'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Contoso'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Wireless Game Controller');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Clean Architecture', 'A craftsman''s guide to software structure and design.', 34.95, 'USD', 40, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Books'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Globex'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Clean Architecture');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Designing Data-Intensive Applications', 'The big ideas behind reliable, scalable, and maintainable systems.', 49.99, 'USD', 18, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Books'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Acme'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Designing Data-Intensive Applications');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Effective Java, 3rd Edition', 'Best practices for the Java platform, from generics to lambdas and streams.', 44.99, 'USD', 22, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Books'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Initech'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Effective Java, 3rd Edition');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Domain-Driven Design Distilled', 'A concise introduction to bounded contexts, aggregates and strategic design.', 29.99, 'USD', 5, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Books'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Northwind'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Domain-Driven Design Distilled');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Ceramic Pour-Over Set', 'Hand-glazed dripper with matching 600 ml carafe.', 42.00, 'USD', 9, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Home'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Initech'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Ceramic Pour-Over Set');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Linen Throw Blanket', 'Stonewashed linen, 130 x 170 cm.', 64.00, 'USD', 7, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Home'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Acme'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Linen Throw Blanket');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Discontinued Lamp', 'Hidden from the storefront (IN_ACTIVE).', 15.00, 'USD', 3, 'IN_ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Home'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Globex'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Discontinued Lamp');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Dimmable Desk Lamp', 'LED desk lamp with five colour temperatures and a USB charging port.', 38.50, 'USD', 26, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Home'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Contoso'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Dimmable Desk Lamp');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Indoor Herb Garden Kit', 'Self-watering planter with basil, mint and parsley seed pods.', 27.00, 'USD', 2, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Home'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Northwind'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Indoor Herb Garden Kit');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Trail Running Backpack 18L', 'Lightweight pack with hydration sleeve, chest strap and reflective details.', 74.90, 'USD', 14, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Sports & Outdoors'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Northwind'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Trail Running Backpack 18L');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Urban Commuter Bike Light Set', 'Rechargeable front and rear lights, 400 lumens, fits any handlebar.', 24.99, 'USD', 60, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Sports & Outdoors'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Acme'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Urban Commuter Bike Light Set');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Insulated Water Bottle 750ml', 'Double-wall stainless steel keeps drinks cold for 24 hours.', 22.00, 'USD', 85, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Sports & Outdoors'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Contoso'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Insulated Water Bottle 750ml');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Digital Sports Stopwatch', 'Lap and split timing with a loud alarm and a lanyard.', 12.50, 'USD', 33, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Sports & Outdoors'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Initech'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Digital Sports Stopwatch');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Mineral Sunscreen SPF 50', 'Reef-friendly, fragrance-free daily sunscreen, 100 ml.', 18.99, 'USD', 40, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Beauty'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Globex'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Mineral Sunscreen SPF 50');
INSERT INTO product (product_name, product_description, price, currency, stock_quantity, status, category_id, brand_id, created_at, updated_at)
SELECT 'Bamboo Makeup Brush Set', 'Eight vegan brushes in a roll-up travel case.', 26.00, 'USD', 11, 'ACTIVE',
       (SELECT category_id FROM category WHERE category_name = 'Beauty'),
       (SELECT brand_id FROM brand WHERE brand_name = 'Contoso'), now(), now()
WHERE NOT EXISTS (SELECT 1 FROM product WHERE product_name = 'Bamboo Makeup Brush Set');

COMMIT;
